从右面切人名：
    - 只考虑 l_office_first2 or l_office_last2 都为0的情况
    - 以前两个结果都为0，删掉后其中一个变为1的话
     ==> 有人名，前面的为官职

In [2]:
import numpy as np
import pandas as pd
from tqdm import tqdm

In [3]:
df = pd.read_csv('../test_files/compare_extract_nozero.csv')

In [4]:
df

,Unnamed: 0,Title,faddress_first2,laddress_first2,faddress_last2,laddress_last2,foffice_first2,loffice_first2,foffice_last2,loffice_last2
0,0,南徐州刺史桂陽王休範,1,0,0,0,0,0,0,0
1,1,侍衛親軍馬軍都指揮使曹,0,0,0,0,1,0,0,0
2,3,南徐州刺史彭城王義康,1,0,0,0,0,0,0,0
3,4,侍衛馬軍都指揮使李繼隆,0,0,0,0,1,0,0,0
4,5,南徐州刺史建平王景素,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
4844,8111,宰相奏事,0,0,0,0,0,1,0,0
4845,8114,編修三司,0,0,0,0,0,0,1,0
4846,8116,涿州留守,0,0,0,1,0,1,0,0
4847,8117,聳動天下,0,0,0,0,0,1,0,0
4848,8119,晉安郡王,0,0,0,0,0,0,0,1

In [5]:
df = df[ df['Title'].apply(lambda x: len(x) >= 5) ]

In [6]:
df

,Unnamed: 0,Title,faddress_first2,laddress_first2,faddress_last2,laddress_last2,foffice_first2,loffice_first2,foffice_last2,loffice_last2
0,0,南徐州刺史桂陽王休範,1,0,0,0,0,0,0,0
1,1,侍衛親軍馬軍都指揮使曹,0,0,0,0,1,0,0,0
2,3,南徐州刺史彭城王義康,1,0,0,0,0,0,0,0
3,4,侍衛馬軍都指揮使李繼隆,0,0,0,0,1,0,0,0
4,5,南徐州刺史建平王景素,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
4518,7372,都統制吳錫,0,0,1,0,0,0,1,0
4521,7377,軍中部統領,0,0,0,0,0,0,0,1
4634,7621,荊鄂都統制,0,0,0,0,0,0,0,1
4714,7786,皇太后處分,0,0,0,0,1,0,0,0
4743,7846,令太常寺丞,0,0,0,0,0,0,0,1

In [15]:
for i in tqdm(range(3)):    # assume the length of the name is at most 3
    count = 0
    for j in df.index:
        if (df['loffice_first2'][j] == 0) | (df['loffice_last2'][j] == 0):
            count += 1

100%|██████████| 3/3 [00:00<00:00, 41.72it/s]

In [16]:
count

2809